import { ShieldCheck, Ticket, Sparkles, Server, ArrowRight, Bot, Zap, Lock } from 'lucide-react';

const features=[['Moderation','Ban, kick, timeout, warn, purge and anti-spam controls.',ShieldCheck],['Welcome','Custom embeds, mentions, images, auto-role and goodbye messages.',Sparkles],['Tickets','Support panels, categories, claim, close and transcript-ready workflows.',Ticket],['Server Control','Central dashboard for modules, commands, logs and settings.',Server]] as const;
const commands=['/ban','/kick','/timeout','/warn','/purge','/ticket','/setup','/serverinfo'];

export default function Home(){return <main className="min-h-screen grid-bg">
<header className="sticky top-0 z-20 border-b border-white/5 bg-[#070812]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-violet-600 to-cyan-500"><Bot size={22}/></div><div><div className="font-black tracking-wide">NAGI BOT</div><div className="text-xs text-slate-500">Discord Control Center</div></div></div><nav className="hidden gap-7 text-sm text-slate-300 md:flex"><a href="#features">Features</a><a href="#commands">Commands</a><a href="#dashboard">Dashboard</a></nav><a className="btn btn-secondary" href="/api/auth/discord">Login with Discord</a></div></header>
<section className="mx-auto max-w-7xl px-6 pb-24 pt-24"><div className="max-w-4xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/5 px-4 py-2 text-sm text-cyan-300"><Zap size={15}/> Premium Discord automation</div><h1 className="text-5xl font-black leading-tight tracking-tight sm:text-7xl">Your server.<br/><span className="gradient-text">Your rules.</span> One dashboard.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-400">NAGI BOT brings moderation, welcome flows, tickets, commands and audit logs into one fast, secure control center.</p><div className="mt-9 flex flex-wrap gap-3"><a className="btn btn-primary" href="https://discord.com/oauth2/authorize?scope=bot%20applications.commands">Add to Discord <ArrowRight size={17} className="ml-2"/></a><a className="btn btn-secondary" href="/api/auth/discord">Login with Discord</a></div></div><div className="mt-16 grid gap-4 sm:grid-cols-3"><div className="glass neon card"><div className="text-3xl font-black">99.9%</div><div className="mt-1 text-sm muted">Designed for reliable operation</div></div><div className="glass neon card"><div className="text-3xl font-black">8+</div><div className="mt-1 text-sm muted">Core slash commands</div></div><div className="glass neon card"><div className="text-3xl font-black">24/7</div><div className="mt-1 text-sm muted">Automation architecture</div></div></div></section>
<section id="features" className="mx-auto max-w-7xl px-6 py-20"><div className="mb-10"><p className="text-sm font-bold uppercase tracking-[.25em] text-cyan-300">Everything in one place</p><h2 className="mt-3 text-4xl font-black">Built for serious communities</h2></div><div className="grid gap-5 md:grid-cols-2">{features.map(([title,text,Icon])=><div key={title} className="glass card neon"><div className="mb-5 grid h-11 w-11 place-items-center rounded-xl bg-violet-500/10 text-violet-300"><Icon size={21}/></div><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 leading-7 text-slate-400">{text}</p></div>)}</div></section>
<section id="commands" className="mx-auto max-w-7xl px-6 py-20"><div className="glass card neon"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.25em] text-emerald-300">Slash commands</p><h2 className="mt-2 text-3xl font-black">Fast, clear, permission-aware</h2></div><div className="flex flex-wrap gap-2">{commands.map(c=><span key={c} className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 font-mono text-sm text-slate-300">{c}</span>)}</div></div></div></section>
<section id="dashboard" className="mx-auto max-w-7xl px-6 py-20"><div className="glass neon rounded-3xl p-8 md:p-12"><div className="max-w-2xl"><Lock className="text-cyan-300"/><h2 className="mt-5 text-4xl font-black">Secure server dashboard</h2><p className="mt-4 leading-7 text-slate-400">OAuth2 login, server-side authorization, PostgreSQL settings, audit trails and modular bot services keep administration safe and scalable.</p><a className="btn btn-primary mt-7" href="/api/auth/discord">Open Dashboard <ArrowRight size={17} className="ml-2"/></a></div></div></section>
<footer className="border-t border-white/5 py-10 text-center text-sm text-slate-500">© 2026 NAGI BOT · Dark + Neon Discord Management</footer></main>}
